---
title: "Chemotype enrichment for PFAS data"
output: html_document
---

This markdown combines code from chemotypes-PFAS.R and chemotypes-stackedplot.R to make the stacked plot. This is just a better commented version of the actual code with just the parts that are essential for plotting. Posting this to the github repo too.
```{r setup, include=FALSE}

#Load libraries, set  wd, load data 

library(tidyr)

#Load condensed chemotypes
tp = read.csv("C:/Users/pthunga/Documents/PhD/PFAS data/results/R/ToxPrints_PFAS-condensed.csv")
#Load consolidated file with morph bmd info
c = read.csv("C:/Users/pthunga/Documents/PhD/PFAS data/results/new data/consolidated_new.csv")
#Get chemical hits in morph
m = c[complete.cases(c$Morph.BMD10),1]

#load lpr lel data
lpr.lel = read.csv("C:/Users/pthunga/Documents/PhD/PFAS data/results/new data/lpr.csv", row.names = 1)
#get chemical hits in LPR
l = row.names(lpr.lel[!(is.na(lpr.lel$Light & is.na(lpr.lel$Dark))),])


epr.lel = read.csv("C:/Users/pthunga/Documents/PhD/PFAS data/results/new data/epr.csv", row.names = 1)
e = row.names(epr.lel[!(is.na(epr.lel$Background) & is.na(epr.lel$Excitatory) & is.na(epr.lel$Refractory)),])

rm(lpr.lel, epr.lel)


```



```{r, include=FALSE }
###  Code to make chemotype plot
getCTcounts <- function(test,other,tp){
  #test will be Dataframe of hits (subset of consolidated file with just hits) and other will be that of non-hits. TP = condensed toxprints
  
  #Get  chemotypes of hit chemicals
  CT_grouped = tp[tp$CAS %in% test$CASRN, -c(2:3)] #remove name and DTSXID, retain toxprints of just hits
  
  CT_grouped[,-1] <- lapply(CT_grouped[,-1], function(x) as.numeric(x)) #convert all col to numeric
  CT_grouped = rbind(CT_grouped, data.frame(CAS= "Count",t(colSums(CT_grouped[,-1])))) #bind a row with sums of all chemotype counts
  CT_grouped = rbind(CT_grouped, data.frame(CAS= "Absent",(nrow(CT_grouped) - CT_grouped[nrow(CT_grouped) ,-1] - 1)))
  
  lrow = nrow(CT_grouped)
  b.CT_counts =data.frame(CT_grouped[(lrow-1):lrow,])
  
  ##get chemotypes of list of chemicals NOT present in hit list to carry out fishers test
  CT_grouped = tp[tp$CAS %in% other$CASRN, -c(2:3)]
  
  
  CT_grouped[,-1] <- lapply(CT_grouped[,-1], function(x) as.numeric(x))
  CT_grouped = rbind(CT_grouped, data.frame(CAS= "Count",t(colSums(CT_grouped[,-1]))))
  CT_grouped = rbind(CT_grouped, data.frame(CAS= "Absent",(nrow(CT_grouped) - CT_grouped[nrow(CT_grouped) ,-1] - 1)))
  
  lrow = nrow(CT_grouped)
  nb.CT_counts =data.frame(CT_grouped[(lrow-1):lrow,])
  
  
  countMatrix = matrix(nrow= 2 ,ncol = 2)
  enrichedCTs = NULL #fisher test for enrichment
  pval = NULL
  for(i in 2:ncol(b.CT_counts)){
    countMatrix[1,1] =  b.CT_counts[1,i]
    countMatrix[2,1] = b.CT_counts[2,i]
    countMatrix[1,2] = nb.CT_counts[1,i]
    countMatrix[2,2] = nb.CT_counts[2,i]
    CT.ftest = fisher.test(countMatrix)
    pval = c(pval, CT.ftest$p.value)
    if(CT.ftest$p.value < 0.05){
      enrichedCTs = c(enrichedCTs, colnames(b.CT_counts[i]))
    }
  }
  
  temp = data.frame(CAS = "p val",t(pval))
  colnames(temp) = c("CAS", colnames(b.CT_counts)[2:37])
  final = rbind(b.CT_counts[1,], nb.CT_counts[1,],temp) #Count in hits,  count in non hits, p value
  # b.CT_counts = rbind(b.CT_counts, temp)
  return(final)
}


```


```{r }

## Get list of enriched chemotypes in morphology by setting "hits" to be only rows with morph biolactiivty. Run CTcounts fn  

hits= c[which(!(is.na(c$Morph.BMD10))),]
not.hits = c[c$chemical_id %in% (setdiff(c$chemical_id,hits$chemical_id)),] #chemical 4434 is duplicated remove one occurence of it
rn = c("117") #adjust row number everytime to remove one occurence of chemical "Perfluorobutanedioic acid" / 4434
not.hits = not.hits[!(row.names(not.hits) %in% rn ),]

df = getCTcounts(hits, not.hits,tp)

tt= data.frame(t(df))
colnames(tt) = c("Hit" ,"Not a hit","pval")
##remove first row 
tt = tt[-c(1),]
tt$chemotype = row.names(tt)
tt = gather(tt, "activity", "count", -pval, -chemotype)
tt$count = as.numeric(as.character(tt$count))
tt$pval = as.numeric(as.character(tt$pval))

tt$enriched = ifelse(tt$pval <= 0.05, "enriched", "not.enriched")
tt = tt[,c(2,3,4,1,5)]

tt$chemotype = as.factor(tt$chemotype)
tt$endPoint = "Morph bioactivity (BMD10)"

main = NULL
main = rbind(main,tt)

## Get list of enriched chemotypes in morphology by setting "hits" to be only rows with EPR biolactiivty. Run CTcounts fn  

hits= c[which(c$chemical_id %in% e ),]
not.hits = c[c$chemical_id %in% (setdiff(c$chemical_id,hits$chemical_id)),] #chemical 4434 is duplicated remove one occurence of it
#rn = c("117")
not.hits = not.hits[!(row.names(not.hits) %in% rn ),]

df = getCTcounts(hits, not.hits,tp)

tt= data.frame(t(df))
colnames(tt) = c("Hit" ,"Not a hit","pval")
##remove first row and 2nd col
tt = tt[-c(1),]
tt$chemotype = row.names(tt)
tt = gather(tt, "activity", "count", -pval, -chemotype)
tt$count = as.numeric(as.character(tt$count))
tt$pval = as.numeric(as.character(tt$pval))

tt$enriched = ifelse(tt$pval <= 0.05, "enriched", "not.enriched")
tt = tt[,c(2,3,4,1,5)]

tt$chemotype = as.factor(tt$chemotype)
tt$endPoint = "EPR bioactivity (LEL)"

main = rbind(main,tt)

# Get list of enriched chemotypes in morphology by setting "hits" to be only rows with LPR biolactiivty. Run CTcounts fn  

hits= c[which(c$chemical_id %in% l ),]
not.hits = c[c$chemical_id %in% (setdiff(c$chemical_id,hits$chemical_id)),] #chemical 4434 is duplicated remove one occurence of it
#rn = c("117")
not.hits = not.hits[!(row.names(not.hits) %in% rn ),]

df = getCTcounts(hits, not.hits,tp)

tt= data.frame(t(df))
colnames(tt) = c("Hit" ,"Not a hit","pval")
##remove first row and 2nd col
tt = tt[-c(1),]
tt$chemotype = row.names(tt)
tt = gather(tt, "activity", "count", -pval, -chemotype)
tt$count = as.numeric(as.character(tt$count))
tt$pval = as.numeric(as.character(tt$pval))

tt$enriched = ifelse(tt$pval <= 0.05, "enriched", "not.enriched")
tt = tt[,c(2,3,4,1,5)]

tt$chemotype = as.factor(tt$chemotype)
tt$endPoint = "LPR bioactivity (LEL)"

main = rbind(main,tt)

```

```{r }


main$activity <- factor(main$activity, levels = c("Hit","Not a hit"))
main = main[order(main$activity, decreasing = T),]
main$endPoint <- factor(main$endPoint, levels = c("EPR bioactivity (LEL)","LPR bioactivity (LEL)","Morph bioactivity (BMD10)"))



rm(list=setdiff(ls(),c("main")))

dummy <- data.frame(endPoint = c("EPR bioactivity (LEL)", "LPR bioactivity (LEL)","Morph bioactivity (BMD10)"),Z = c(21, 34,31)) # to add vertical line with number of hits 
dummy$X <- factor(dummy$endPoint, levels = c( "EPR bioactivity (LEL)","LPR bioactivity (LEL)","Morph bioactivity (BMD10)"))

```

```{r }
p = ggplot(data = main, aes(x = chemotype, y =count, fill = factor(activity, levels=c("Not a hit","Hit")), alpha = enriched == "enriched")) +
  geom_bar(stat = "identity") + geom_hline(data = dummy, aes(yintercept = Z), linetype = 'dotted', color = "#FF4B4B" )+
  facet_wrap(endPoint ~ ., ncol = 3) +
  scale_fill_manual(values=c( "#3EBDFF", "#FF4B4B")) +  # blue #3EBDFF
  scale_y_continuous(breaks = seq(0, 140, by = 20)) + 
  scale_alpha_discrete(range = c(0.5, 0.9)) + 
  coord_flip() + 
  theme(panel.border = element_rect(linetype = "dashed", fill = NA)) +  
  guides(fill=guide_legend(title="Activity"), alpha = FALSE) + 
  #theme(legend.position = "none") +
  # ggtitle("morphology") +
  xlab("Chemotype") + ylab("# of chemicals") + scale_alpha_discrete(range = c(0.25, 1))

p

ggsave("C:/Users/pthunga/Documents/PhD/PFAS data/results/new data/CT_stacked-allEP-new.jpeg",plot=p, width = 25.75, height = 14.85,units="cm", dpi=300)

#####
```

